[2024-04-08T14:44:19.047+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:10:00+00:00 [queued]>
[2024-04-08T14:44:19.090+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:10:00+00:00 [queued]>
[2024-04-08T14:44:19.098+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-08T14:44:19.262+0000] {taskinstance.py:2217} INFO - Executing <Task(CassandraTableSensor): cassandra_sensor> on 2024-04-08 00:10:00+00:00
[2024-04-08T14:44:19.318+0000] {standard_task_runner.py:60} INFO - Started process 310 to run task
[2024-04-08T14:44:19.374+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cassandra_sensor_dag', 'cassandra_sensor', 'scheduled__2024-04-08T00:10:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp2hiiy0xv']
[2024-04-08T14:44:19.408+0000] {standard_task_runner.py:88} INFO - Job 44: Subtask cassandra_sensor
[2024-04-08T14:44:19.717+0000] {task_command.py:423} INFO - Running <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:10:00+00:00 [running]> on host c2d2cc8ff432
[2024-04-08T14:44:20.424+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cassandra_sensor_dag' AIRFLOW_CTX_TASK_ID='cassandra_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T00:10:00+00:00'
[2024-04-08T14:44:20.459+0000] {table.py:65} INFO - Sensor check existence of table: users
[2024-04-08T14:44:20.528+0000] {base.py:83} INFO - Using connection ID 'cassandra_conn' for task execution.
[2024-04-08T14:44:20.544+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-04-08T14:44:20.559+0000] {cassandra.py:128} WARNING - [control connection] Error connecting to 127.0.0.1:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3577, in cassandra.cluster.ControlConnection._reconnect_internal
  File "cassandra/cluster.py", line 3599, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1670, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 846, in cassandra.connection.Connection.factory
  File "/home/airflow/.local/lib/python3.8/site-packages/cassandra/io/libevreactor.py", line 266, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 951, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused
[2024-04-08T14:44:20.566+0000] {cassandra.py:128} ERROR - Control connection failed to connect, shutting down Cluster:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 1740, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3543, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3588, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
[2024-04-08T14:44:20.569+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/sensors/table.py", line 67, in poke
    return hook.table_exists(self.table)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 185, in table_exists
    cluster_metadata = self.get_conn().cluster.metadata
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 128, in get_conn
    self.session = self.cluster.connect(self.keyspace)
  File "cassandra/cluster.py", line 1717, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1753, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1740, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3543, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3588, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
[2024-04-08T14:44:20.607+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=cassandra_sensor_dag, task_id=cassandra_sensor, execution_date=20240408T001000, start_date=20240408T144419, end_date=20240408T144420
[2024-04-08T14:44:20.728+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 44 for task cassandra_sensor (('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")}); 310)
[2024-04-08T14:44:20.802+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T14:44:20.946+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-08T14:48:38.585+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:10:00+00:00 [queued]>
[2024-04-08T14:48:38.838+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:10:00+00:00 [queued]>
[2024-04-08T14:48:38.854+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-08T14:48:40.150+0000] {taskinstance.py:2217} INFO - Executing <Task(CassandraTableSensor): cassandra_sensor> on 2024-04-08 00:10:00+00:00
[2024-04-08T14:48:40.500+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cassandra_sensor_dag', 'cassandra_sensor', 'scheduled__2024-04-08T00:10:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpva9z5fva']
[2024-04-08T14:48:40.683+0000] {standard_task_runner.py:88} INFO - Job 63: Subtask cassandra_sensor
[2024-04-08T14:48:40.390+0000] {standard_task_runner.py:60} INFO - Started process 465 to run task
[2024-04-08T14:48:41.595+0000] {task_command.py:423} INFO - Running <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:10:00+00:00 [running]> on host c2d2cc8ff432
[2024-04-08T14:48:42.206+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cassandra_sensor_dag' AIRFLOW_CTX_TASK_ID='cassandra_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T00:10:00+00:00'
[2024-04-08T14:48:42.218+0000] {table.py:65} INFO - Sensor check existence of table: users
[2024-04-08T14:48:42.266+0000] {base.py:83} INFO - Using connection ID 'cassandra_conn' for task execution.
[2024-04-08T14:48:42.272+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-04-08T14:48:42.325+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 66 to 65 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T14:48:42.364+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 65 to 5 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T14:48:42.807+0000] {thread.py:57} WARNING - Failed to create connection pool for new host 172.21.0.4:9042:
Traceback (most recent call last):
  File "cassandra/connection.py", line 1503, in cassandra.connection.Connection.set_keyspace_blocking
  File "cassandra/connection.py", line 1082, in cassandra.connection.Connection.wait_for_response
  File "cassandra/connection.py", line 1129, in cassandra.connection.Connection.wait_for_responses
  File "cassandra/connection.py", line 1124, in cassandra.connection.Connection.wait_for_responses
  File "cassandra/connection.py", line 1634, in cassandra.connection.ResponseWaiter.deliver
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace 'test_dna' does not exist"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cassandra/cluster.py", line 3234, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool
  File "cassandra/pool.py", line 409, in cassandra.pool.HostConnection.__init__
  File "cassandra/connection.py", line 1511, in cassandra.connection.Connection.set_keyspace_blocking
cassandra.connection.ConnectionException: Problem while setting keyspace: InvalidRequest('Error from server: code=2200 [Invalid query] message="Keyspace \'test_dna\' does not exist"')
[2024-04-08T14:48:42.832+0000] {thread.py:57} WARNING - Host 172.21.0.4:9042 has been marked down
[2024-04-08T14:48:42.834+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/sensors/table.py", line 67, in poke
    return hook.table_exists(self.table)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 185, in table_exists
    cluster_metadata = self.get_conn().cluster.metadata
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 128, in get_conn
    self.session = self.cluster.connect(self.keyspace)
  File "cassandra/cluster.py", line 1765, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1822, in cassandra.cluster.Cluster._new_session
  File "cassandra/cluster.py", line 2603, in cassandra.cluster.Session.__init__
cassandra.cluster.NoHostAvailable: ("Unable to connect to any servers using keyspace 'test_dna'", ['172.21.0.4'])
[2024-04-08T14:48:42.858+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=cassandra_sensor_dag, task_id=cassandra_sensor, execution_date=20240408T001000, start_date=20240408T144838, end_date=20240408T144842
[2024-04-08T14:48:42.949+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 63 for task cassandra_sensor (("Unable to connect to any servers using keyspace 'test_dna'", ['172.21.0.4']); 465)
[2024-04-08T14:48:43.088+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T14:48:43.391+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-08T15:04:18.022+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:10:00+00:00 [queued]>
[2024-04-08T15:04:18.279+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:10:00+00:00 [queued]>
[2024-04-08T15:04:18.319+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-08T15:04:18.714+0000] {taskinstance.py:2217} INFO - Executing <Task(CassandraTableSensor): cassandra_sensor> on 2024-04-08 00:10:00+00:00
[2024-04-08T15:04:18.802+0000] {standard_task_runner.py:60} INFO - Started process 1528 to run task
[2024-04-08T15:04:18.916+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cassandra_sensor_dag', 'cassandra_sensor', 'scheduled__2024-04-08T00:10:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpcg5nbxem']
[2024-04-08T15:04:18.953+0000] {standard_task_runner.py:88} INFO - Job 124: Subtask cassandra_sensor
[2024-04-08T15:04:20.496+0000] {task_command.py:423} INFO - Running <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:10:00+00:00 [running]> on host c2d2cc8ff432
[2024-04-08T15:04:21.628+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cassandra_sensor_dag' AIRFLOW_CTX_TASK_ID='cassandra_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T00:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T00:10:00+00:00'
[2024-04-08T15:04:21.662+0000] {table.py:65} INFO - Sensor check existence of table: users
[2024-04-08T15:04:21.860+0000] {base.py:83} INFO - Using connection ID 'cassandra_conn' for task execution.
[2024-04-08T15:04:21.915+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-04-08T15:04:22.000+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 66 to 65 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T15:04:22.034+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 65 to 5 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T15:04:22.619+0000] {base.py:295} INFO - Success criteria met. Exiting.
[2024-04-08T15:04:22.732+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=cassandra_sensor_dag, task_id=cassandra_sensor, execution_date=20240408T001000, start_date=20240408T150418, end_date=20240408T150422
[2024-04-08T15:04:23.609+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T15:04:24.014+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
