[2024-04-08T14:44:44.774+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T01:10:00+00:00 [queued]>
[2024-04-08T14:44:44.800+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T01:10:00+00:00 [queued]>
[2024-04-08T14:44:44.802+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-08T14:44:44.856+0000] {taskinstance.py:2217} INFO - Executing <Task(CassandraTableSensor): cassandra_sensor> on 2024-04-08 01:10:00+00:00
[2024-04-08T14:44:44.882+0000] {standard_task_runner.py:60} INFO - Started process 371 to run task
[2024-04-08T14:44:44.897+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cassandra_sensor_dag', 'cassandra_sensor', 'scheduled__2024-04-08T01:10:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpuruii4eu']
[2024-04-08T14:44:44.907+0000] {standard_task_runner.py:88} INFO - Job 59: Subtask cassandra_sensor
[2024-04-08T14:44:45.086+0000] {task_command.py:423} INFO - Running <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T01:10:00+00:00 [running]> on host c2d2cc8ff432
[2024-04-08T14:44:45.355+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cassandra_sensor_dag' AIRFLOW_CTX_TASK_ID='cassandra_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T01:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T01:10:00+00:00'
[2024-04-08T14:44:45.364+0000] {table.py:65} INFO - Sensor check existence of table: users
[2024-04-08T14:44:45.408+0000] {base.py:83} INFO - Using connection ID 'cassandra_conn' for task execution.
[2024-04-08T14:44:45.416+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-04-08T14:44:45.425+0000] {cassandra.py:128} WARNING - [control connection] Error connecting to 127.0.0.1:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3577, in cassandra.cluster.ControlConnection._reconnect_internal
  File "cassandra/cluster.py", line 3599, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1670, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 846, in cassandra.connection.Connection.factory
  File "/home/airflow/.local/lib/python3.8/site-packages/cassandra/io/libevreactor.py", line 266, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 951, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused
[2024-04-08T14:44:45.430+0000] {cassandra.py:128} ERROR - Control connection failed to connect, shutting down Cluster:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 1740, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3543, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3588, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
[2024-04-08T14:44:45.433+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/sensors/table.py", line 67, in poke
    return hook.table_exists(self.table)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 185, in table_exists
    cluster_metadata = self.get_conn().cluster.metadata
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 128, in get_conn
    self.session = self.cluster.connect(self.keyspace)
  File "cassandra/cluster.py", line 1717, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1753, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1740, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3543, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3588, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
[2024-04-08T14:44:45.478+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=cassandra_sensor_dag, task_id=cassandra_sensor, execution_date=20240408T011000, start_date=20240408T144444, end_date=20240408T144445
[2024-04-08T14:44:45.540+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 59 for task cassandra_sensor (('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")}); 371)
[2024-04-08T14:44:45.577+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T14:44:45.791+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-08T14:48:57.789+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T01:10:00+00:00 [queued]>
[2024-04-08T14:48:57.810+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T01:10:00+00:00 [queued]>
[2024-04-08T14:48:57.811+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-08T14:48:57.842+0000] {taskinstance.py:2217} INFO - Executing <Task(CassandraTableSensor): cassandra_sensor> on 2024-04-08 01:10:00+00:00
[2024-04-08T14:48:57.855+0000] {standard_task_runner.py:60} INFO - Started process 578 to run task
[2024-04-08T14:48:57.862+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cassandra_sensor_dag', 'cassandra_sensor', 'scheduled__2024-04-08T01:10:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpbyn1vj8b']
[2024-04-08T14:48:57.870+0000] {standard_task_runner.py:88} INFO - Job 75: Subtask cassandra_sensor
[2024-04-08T14:48:57.970+0000] {task_command.py:423} INFO - Running <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T01:10:00+00:00 [running]> on host c2d2cc8ff432
[2024-04-08T14:48:58.116+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cassandra_sensor_dag' AIRFLOW_CTX_TASK_ID='cassandra_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T01:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T01:10:00+00:00'
[2024-04-08T14:48:58.119+0000] {table.py:65} INFO - Sensor check existence of table: users
[2024-04-08T14:48:58.134+0000] {base.py:83} INFO - Using connection ID 'cassandra_conn' for task execution.
[2024-04-08T14:48:58.138+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-04-08T14:48:58.145+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 66 to 65 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T14:48:58.148+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 65 to 5 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T14:48:58.215+0000] {thread.py:57} WARNING - Failed to create connection pool for new host 172.21.0.4:9042:
Traceback (most recent call last):
  File "cassandra/connection.py", line 1503, in cassandra.connection.Connection.set_keyspace_blocking
  File "cassandra/connection.py", line 1082, in cassandra.connection.Connection.wait_for_response
  File "cassandra/connection.py", line 1129, in cassandra.connection.Connection.wait_for_responses
  File "cassandra/connection.py", line 1124, in cassandra.connection.Connection.wait_for_responses
  File "cassandra/connection.py", line 1634, in cassandra.connection.ResponseWaiter.deliver
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace 'test_dna' does not exist"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cassandra/cluster.py", line 3234, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool
  File "cassandra/pool.py", line 409, in cassandra.pool.HostConnection.__init__
  File "cassandra/connection.py", line 1511, in cassandra.connection.Connection.set_keyspace_blocking
cassandra.connection.ConnectionException: Problem while setting keyspace: InvalidRequest('Error from server: code=2200 [Invalid query] message="Keyspace \'test_dna\' does not exist"')
[2024-04-08T14:48:58.219+0000] {thread.py:57} WARNING - Host 172.21.0.4:9042 has been marked down
[2024-04-08T14:48:58.220+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/sensors/table.py", line 67, in poke
    return hook.table_exists(self.table)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 185, in table_exists
    cluster_metadata = self.get_conn().cluster.metadata
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 128, in get_conn
    self.session = self.cluster.connect(self.keyspace)
  File "cassandra/cluster.py", line 1765, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1822, in cassandra.cluster.Cluster._new_session
  File "cassandra/cluster.py", line 2603, in cassandra.cluster.Session.__init__
cassandra.cluster.NoHostAvailable: ("Unable to connect to any servers using keyspace 'test_dna'", ['172.21.0.4'])
[2024-04-08T14:48:58.241+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=cassandra_sensor_dag, task_id=cassandra_sensor, execution_date=20240408T011000, start_date=20240408T144857, end_date=20240408T144858
[2024-04-08T14:48:58.263+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 75 for task cassandra_sensor (("Unable to connect to any servers using keyspace 'test_dna'", ['172.21.0.4']); 578)
[2024-04-08T14:48:58.317+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T14:48:58.357+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-08T15:04:13.556+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T01:10:00+00:00 [queued]>
[2024-04-08T15:04:13.720+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T01:10:00+00:00 [queued]>
[2024-04-08T15:04:13.814+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-08T15:04:14.493+0000] {taskinstance.py:2217} INFO - Executing <Task(CassandraTableSensor): cassandra_sensor> on 2024-04-08 01:10:00+00:00
[2024-04-08T15:04:15.254+0000] {standard_task_runner.py:60} INFO - Started process 1521 to run task
[2024-04-08T15:04:15.535+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cassandra_sensor_dag', 'cassandra_sensor', 'scheduled__2024-04-08T01:10:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp3qwty4w_']
[2024-04-08T15:04:15.700+0000] {standard_task_runner.py:88} INFO - Job 123: Subtask cassandra_sensor
[2024-04-08T15:04:16.927+0000] {task_command.py:423} INFO - Running <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T01:10:00+00:00 [running]> on host c2d2cc8ff432
[2024-04-08T15:04:19.145+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cassandra_sensor_dag' AIRFLOW_CTX_TASK_ID='cassandra_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T01:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T01:10:00+00:00'
[2024-04-08T15:04:19.221+0000] {table.py:65} INFO - Sensor check existence of table: users
[2024-04-08T15:04:19.349+0000] {base.py:83} INFO - Using connection ID 'cassandra_conn' for task execution.
[2024-04-08T15:04:19.359+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-04-08T15:04:19.399+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 66 to 65 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T15:04:19.413+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 65 to 5 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T15:04:19.870+0000] {base.py:295} INFO - Success criteria met. Exiting.
[2024-04-08T15:04:20.038+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=cassandra_sensor_dag, task_id=cassandra_sensor, execution_date=20240408T011000, start_date=20240408T150413, end_date=20240408T150420
[2024-04-08T15:04:21.097+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T15:04:22.236+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
