[2024-04-08T14:44:38.595+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:40:00+00:00 [queued]>
[2024-04-08T14:44:38.635+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:40:00+00:00 [queued]>
[2024-04-08T14:44:38.637+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-08T14:44:38.836+0000] {taskinstance.py:2217} INFO - Executing <Task(CassandraTableSensor): cassandra_sensor> on 2024-04-08 00:40:00+00:00
[2024-04-08T14:44:38.866+0000] {standard_task_runner.py:60} INFO - Started process 352 to run task
[2024-04-08T14:44:38.922+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cassandra_sensor_dag', 'cassandra_sensor', 'scheduled__2024-04-08T00:40:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp039ou7hv']
[2024-04-08T14:44:38.965+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask cassandra_sensor
[2024-04-08T14:44:39.418+0000] {task_command.py:423} INFO - Running <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:40:00+00:00 [running]> on host c2d2cc8ff432
[2024-04-08T14:44:40.065+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cassandra_sensor_dag' AIRFLOW_CTX_TASK_ID='cassandra_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T00:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T00:40:00+00:00'
[2024-04-08T14:44:40.083+0000] {table.py:65} INFO - Sensor check existence of table: users
[2024-04-08T14:44:40.144+0000] {base.py:83} INFO - Using connection ID 'cassandra_conn' for task execution.
[2024-04-08T14:44:40.149+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-04-08T14:44:40.160+0000] {cassandra.py:128} WARNING - [control connection] Error connecting to 127.0.0.1:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3577, in cassandra.cluster.ControlConnection._reconnect_internal
  File "cassandra/cluster.py", line 3599, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1670, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 846, in cassandra.connection.Connection.factory
  File "/home/airflow/.local/lib/python3.8/site-packages/cassandra/io/libevreactor.py", line 266, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 951, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused
[2024-04-08T14:44:40.176+0000] {cassandra.py:128} ERROR - Control connection failed to connect, shutting down Cluster:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 1740, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3543, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3588, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
[2024-04-08T14:44:40.191+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/sensors/table.py", line 67, in poke
    return hook.table_exists(self.table)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 185, in table_exists
    cluster_metadata = self.get_conn().cluster.metadata
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 128, in get_conn
    self.session = self.cluster.connect(self.keyspace)
  File "cassandra/cluster.py", line 1717, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1753, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1740, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3543, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3588, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
[2024-04-08T14:44:40.247+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=cassandra_sensor_dag, task_id=cassandra_sensor, execution_date=20240408T004000, start_date=20240408T144438, end_date=20240408T144440
[2024-04-08T14:44:40.296+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 53 for task cassandra_sensor (('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")}); 352)
[2024-04-08T14:44:40.352+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T14:44:40.457+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-08T14:48:47.020+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:40:00+00:00 [queued]>
[2024-04-08T14:48:47.190+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:40:00+00:00 [queued]>
[2024-04-08T14:48:47.197+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-08T14:48:47.460+0000] {taskinstance.py:2217} INFO - Executing <Task(CassandraTableSensor): cassandra_sensor> on 2024-04-08 00:40:00+00:00
[2024-04-08T14:48:47.500+0000] {standard_task_runner.py:60} INFO - Started process 521 to run task
[2024-04-08T14:48:47.573+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cassandra_sensor_dag', 'cassandra_sensor', 'scheduled__2024-04-08T00:40:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpmwgqpx3v']
[2024-04-08T14:48:47.583+0000] {standard_task_runner.py:88} INFO - Job 69: Subtask cassandra_sensor
[2024-04-08T14:48:48.210+0000] {task_command.py:423} INFO - Running <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:40:00+00:00 [running]> on host c2d2cc8ff432
[2024-04-08T14:48:48.915+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cassandra_sensor_dag' AIRFLOW_CTX_TASK_ID='cassandra_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T00:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T00:40:00+00:00'
[2024-04-08T14:48:48.929+0000] {table.py:65} INFO - Sensor check existence of table: users
[2024-04-08T14:48:48.980+0000] {base.py:83} INFO - Using connection ID 'cassandra_conn' for task execution.
[2024-04-08T14:48:48.990+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-04-08T14:48:49.050+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 66 to 65 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T14:48:49.080+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 65 to 5 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T14:48:49.576+0000] {thread.py:57} WARNING - Failed to create connection pool for new host 172.21.0.4:9042:
Traceback (most recent call last):
  File "cassandra/connection.py", line 1503, in cassandra.connection.Connection.set_keyspace_blocking
  File "cassandra/connection.py", line 1082, in cassandra.connection.Connection.wait_for_response
  File "cassandra/connection.py", line 1129, in cassandra.connection.Connection.wait_for_responses
  File "cassandra/connection.py", line 1124, in cassandra.connection.Connection.wait_for_responses
  File "cassandra/connection.py", line 1634, in cassandra.connection.ResponseWaiter.deliver
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace 'test_dna' does not exist"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cassandra/cluster.py", line 3234, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool
  File "cassandra/pool.py", line 409, in cassandra.pool.HostConnection.__init__
  File "cassandra/connection.py", line 1511, in cassandra.connection.Connection.set_keyspace_blocking
cassandra.connection.ConnectionException: Problem while setting keyspace: InvalidRequest('Error from server: code=2200 [Invalid query] message="Keyspace \'test_dna\' does not exist"')
[2024-04-08T14:48:49.609+0000] {thread.py:57} WARNING - Host 172.21.0.4:9042 has been marked down
[2024-04-08T14:48:49.619+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/sensors/table.py", line 67, in poke
    return hook.table_exists(self.table)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 185, in table_exists
    cluster_metadata = self.get_conn().cluster.metadata
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 128, in get_conn
    self.session = self.cluster.connect(self.keyspace)
  File "cassandra/cluster.py", line 1765, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1822, in cassandra.cluster.Cluster._new_session
  File "cassandra/cluster.py", line 2603, in cassandra.cluster.Session.__init__
cassandra.cluster.NoHostAvailable: ("Unable to connect to any servers using keyspace 'test_dna'", ['172.21.0.4'])
[2024-04-08T14:48:49.662+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=cassandra_sensor_dag, task_id=cassandra_sensor, execution_date=20240408T004000, start_date=20240408T144847, end_date=20240408T144849
[2024-04-08T14:48:49.997+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 69 for task cassandra_sensor (("Unable to connect to any servers using keyspace 'test_dna'", ['172.21.0.4']); 521)
[2024-04-08T14:48:50.168+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T14:48:50.533+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-08T15:03:37.331+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:40:00+00:00 [queued]>
[2024-04-08T15:03:37.809+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:40:00+00:00 [queued]>
[2024-04-08T15:03:37.895+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-08T15:03:39.137+0000] {taskinstance.py:2217} INFO - Executing <Task(CassandraTableSensor): cassandra_sensor> on 2024-04-08 00:40:00+00:00
[2024-04-08T15:03:39.557+0000] {standard_task_runner.py:60} INFO - Started process 1441 to run task
[2024-04-08T15:03:39.846+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cassandra_sensor_dag', 'cassandra_sensor', 'scheduled__2024-04-08T00:40:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp_qukreol']
[2024-04-08T15:03:39.918+0000] {standard_task_runner.py:88} INFO - Job 115: Subtask cassandra_sensor
[2024-04-08T15:03:41.880+0000] {task_command.py:423} INFO - Running <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:40:00+00:00 [running]> on host c2d2cc8ff432
[2024-04-08T15:03:45.977+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cassandra_sensor_dag' AIRFLOW_CTX_TASK_ID='cassandra_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T00:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T00:40:00+00:00'
[2024-04-08T15:03:46.014+0000] {table.py:65} INFO - Sensor check existence of table: users
[2024-04-08T15:03:46.268+0000] {base.py:83} INFO - Using connection ID 'cassandra_conn' for task execution.
[2024-04-08T15:03:46.400+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-04-08T15:03:46.782+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 66 to 65 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T15:03:46.860+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 65 to 5 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T15:03:47.607+0000] {base.py:295} INFO - Success criteria met. Exiting.
[2024-04-08T15:03:47.841+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=cassandra_sensor_dag, task_id=cassandra_sensor, execution_date=20240408T004000, start_date=20240408T150337, end_date=20240408T150347
[2024-04-08T15:03:49.241+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T15:03:50.317+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
