[2024-04-08T14:44:36.218+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:30:00+00:00 [queued]>
[2024-04-08T14:44:36.274+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:30:00+00:00 [queued]>
[2024-04-08T14:44:36.275+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-08T14:44:36.907+0000] {taskinstance.py:2217} INFO - Executing <Task(CassandraTableSensor): cassandra_sensor> on 2024-04-08 00:30:00+00:00
[2024-04-08T14:44:36.952+0000] {standard_task_runner.py:60} INFO - Started process 341 to run task
[2024-04-08T14:44:36.967+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cassandra_sensor_dag', 'cassandra_sensor', 'scheduled__2024-04-08T00:30:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpb8vpw9mc']
[2024-04-08T14:44:36.993+0000] {standard_task_runner.py:88} INFO - Job 51: Subtask cassandra_sensor
[2024-04-08T14:44:37.287+0000] {task_command.py:423} INFO - Running <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:30:00+00:00 [running]> on host c2d2cc8ff432
[2024-04-08T14:44:37.782+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cassandra_sensor_dag' AIRFLOW_CTX_TASK_ID='cassandra_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T00:30:00+00:00'
[2024-04-08T14:44:37.791+0000] {table.py:65} INFO - Sensor check existence of table: users
[2024-04-08T14:44:37.861+0000] {base.py:83} INFO - Using connection ID 'cassandra_conn' for task execution.
[2024-04-08T14:44:37.891+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-04-08T14:44:37.906+0000] {cassandra.py:128} WARNING - [control connection] Error connecting to 127.0.0.1:9042:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 3577, in cassandra.cluster.ControlConnection._reconnect_internal
  File "cassandra/cluster.py", line 3599, in cassandra.cluster.ControlConnection._try_connect
  File "cassandra/cluster.py", line 1670, in cassandra.cluster.Cluster.connection_factory
  File "cassandra/connection.py", line 846, in cassandra.connection.Connection.factory
  File "/home/airflow/.local/lib/python3.8/site-packages/cassandra/io/libevreactor.py", line 266, in __init__
    self._connect_socket()
  File "cassandra/connection.py", line 951, in cassandra.connection.Connection._connect_socket
ConnectionRefusedError: [Errno 111] Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused
[2024-04-08T14:44:37.910+0000] {cassandra.py:128} ERROR - Control connection failed to connect, shutting down Cluster:
Traceback (most recent call last):
  File "cassandra/cluster.py", line 1740, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3543, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3588, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
[2024-04-08T14:44:37.920+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/sensors/table.py", line 67, in poke
    return hook.table_exists(self.table)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 185, in table_exists
    cluster_metadata = self.get_conn().cluster.metadata
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 128, in get_conn
    self.session = self.cluster.connect(self.keyspace)
  File "cassandra/cluster.py", line 1717, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1753, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1740, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 3543, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 3588, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
[2024-04-08T14:44:37.950+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=cassandra_sensor_dag, task_id=cassandra_sensor, execution_date=20240408T003000, start_date=20240408T144436, end_date=20240408T144437
[2024-04-08T14:44:38.018+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 51 for task cassandra_sensor (('Unable to connect to any servers', {'127.0.0.1:9042': ConnectionRefusedError(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")}); 341)
[2024-04-08T14:44:38.123+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T14:44:38.233+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-08T14:48:45.307+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:30:00+00:00 [queued]>
[2024-04-08T14:48:45.390+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:30:00+00:00 [queued]>
[2024-04-08T14:48:45.412+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-08T14:48:45.554+0000] {taskinstance.py:2217} INFO - Executing <Task(CassandraTableSensor): cassandra_sensor> on 2024-04-08 00:30:00+00:00
[2024-04-08T14:48:45.576+0000] {standard_task_runner.py:60} INFO - Started process 502 to run task
[2024-04-08T14:48:45.618+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cassandra_sensor_dag', 'cassandra_sensor', 'scheduled__2024-04-08T00:30:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp6g9ggqd1']
[2024-04-08T14:48:45.635+0000] {standard_task_runner.py:88} INFO - Job 67: Subtask cassandra_sensor
[2024-04-08T14:48:46.008+0000] {task_command.py:423} INFO - Running <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:30:00+00:00 [running]> on host c2d2cc8ff432
[2024-04-08T14:48:46.570+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cassandra_sensor_dag' AIRFLOW_CTX_TASK_ID='cassandra_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T00:30:00+00:00'
[2024-04-08T14:48:46.601+0000] {table.py:65} INFO - Sensor check existence of table: users
[2024-04-08T14:48:46.646+0000] {base.py:83} INFO - Using connection ID 'cassandra_conn' for task execution.
[2024-04-08T14:48:46.664+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-04-08T14:48:46.691+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 66 to 65 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T14:48:46.734+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 65 to 5 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T14:48:47.211+0000] {thread.py:57} WARNING - Failed to create connection pool for new host 172.21.0.4:9042:
Traceback (most recent call last):
  File "cassandra/connection.py", line 1503, in cassandra.connection.Connection.set_keyspace_blocking
  File "cassandra/connection.py", line 1082, in cassandra.connection.Connection.wait_for_response
  File "cassandra/connection.py", line 1129, in cassandra.connection.Connection.wait_for_responses
  File "cassandra/connection.py", line 1124, in cassandra.connection.Connection.wait_for_responses
  File "cassandra/connection.py", line 1634, in cassandra.connection.ResponseWaiter.deliver
cassandra.InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace 'test_dna' does not exist"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cassandra/cluster.py", line 3234, in cassandra.cluster.Session.add_or_renew_pool.run_add_or_renew_pool
  File "cassandra/pool.py", line 409, in cassandra.pool.HostConnection.__init__
  File "cassandra/connection.py", line 1511, in cassandra.connection.Connection.set_keyspace_blocking
cassandra.connection.ConnectionException: Problem while setting keyspace: InvalidRequest('Error from server: code=2200 [Invalid query] message="Keyspace \'test_dna\' does not exist"')
[2024-04-08T14:48:47.241+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 265, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 247, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/sensors/table.py", line 67, in poke
    return hook.table_exists(self.table)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 185, in table_exists
    cluster_metadata = self.get_conn().cluster.metadata
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/cassandra/hooks/cassandra.py", line 128, in get_conn
    self.session = self.cluster.connect(self.keyspace)
  File "cassandra/cluster.py", line 1765, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1822, in cassandra.cluster.Cluster._new_session
  File "cassandra/cluster.py", line 2603, in cassandra.cluster.Session.__init__
cassandra.cluster.NoHostAvailable: ("Unable to connect to any servers using keyspace 'test_dna'", ['172.21.0.4'])
[2024-04-08T14:48:47.240+0000] {thread.py:57} WARNING - Host 172.21.0.4:9042 has been marked down
[2024-04-08T14:48:47.319+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=cassandra_sensor_dag, task_id=cassandra_sensor, execution_date=20240408T003000, start_date=20240408T144845, end_date=20240408T144847
[2024-04-08T14:48:47.472+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 67 for task cassandra_sensor (("Unable to connect to any servers using keyspace 'test_dna'", ['172.21.0.4']); 502)
[2024-04-08T14:48:47.668+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-08T14:48:47.809+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-08T15:03:34.525+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:30:00+00:00 [queued]>
[2024-04-08T15:03:34.758+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:30:00+00:00 [queued]>
[2024-04-08T15:03:34.814+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-08T15:03:35.591+0000] {taskinstance.py:2217} INFO - Executing <Task(CassandraTableSensor): cassandra_sensor> on 2024-04-08 00:30:00+00:00
[2024-04-08T15:03:35.822+0000] {standard_task_runner.py:60} INFO - Started process 1437 to run task
[2024-04-08T15:03:35.980+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cassandra_sensor_dag', 'cassandra_sensor', 'scheduled__2024-04-08T00:30:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp6s44oljs']
[2024-04-08T15:03:36.142+0000] {standard_task_runner.py:88} INFO - Job 114: Subtask cassandra_sensor
[2024-04-08T15:03:37.705+0000] {task_command.py:423} INFO - Running <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-08T00:30:00+00:00 [running]> on host c2d2cc8ff432
[2024-04-08T15:03:39.822+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cassandra_sensor_dag' AIRFLOW_CTX_TASK_ID='cassandra_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-08T00:30:00+00:00'
[2024-04-08T15:03:39.872+0000] {table.py:65} INFO - Sensor check existence of table: users
[2024-04-08T15:03:40.097+0000] {base.py:83} INFO - Using connection ID 'cassandra_conn' for task execution.
[2024-04-08T15:03:40.152+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/apache/cassandra/hooks/cassandra.py:120: DeprecationWarning: Legacy execution parameters will be removed in 4.0. Consider using execution profiles.
  self.cluster = Cluster(**conn_config)

[2024-04-08T15:03:40.440+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 66 to 65 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T15:03:40.524+0000] {cassandra.py:128} WARNING - Downgrading core protocol version from 65 to 5 for 172.21.0.4:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-04-08T15:03:41.848+0000] {base.py:295} INFO - Success criteria met. Exiting.
[2024-04-08T15:03:41.991+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=cassandra_sensor_dag, task_id=cassandra_sensor, execution_date=20240408T003000, start_date=20240408T150334, end_date=20240408T150341
[2024-04-08T15:03:42.840+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T15:03:44.263+0000] {taskinstance.py:3312} INFO - 1 downstream tasks scheduled from follow-on schedule check
